In [2]:
import numpy as np
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in range(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)

In [7]:
print("{} and {}".format(syn1,syn0))


[[ 7.80799708]
 [-7.68892209]
 [ 7.37195962]
 [-7.71477706]] and [[-3.93450268 -5.81319518  4.16728997  5.20366414]
 [-3.8943954   5.41749663  4.16455113 -5.62516369]
 [ 6.25621912  3.26448461 -1.52116745  3.17589804]]
